import {_electron as electron} from '../notes/node_modules/playwright-core/index.mjs';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),profile=path.join(root,'.build-tmp','studio-ui-profile-'+Date.now()),fixtures=path.join(root,'.build-tmp','studio-fixtures');
fs.mkdirSync(fixtures,{recursive:true});fs.mkdirSync(path.join(profile,'media'),{recursive:true});
const sampleRate=22050,seconds=18,pcm=Buffer.alloc(sampleRate*seconds*2),wav=Buffer.alloc(44+pcm.length);
for(let i=0;i<sampleRate*seconds;i++){const t=i/sampleRate;const envelope=Math.exp(-(t%.5)*15);pcm.writeInt16LE(Math.round((Math.sin(2*Math.PI*220*t)*.15+Math.sin(2*Math.PI*62*t)*envelope*.35)*32767),i*2);}
wav.write('RIFF');wav.writeUInt32LE(36+pcm.length,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(sampleRate,24);wav.writeUInt32LE(sampleRate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(pcm.length,40);pcm.copy(wav,44);
for(const name of ['01 - Echo Sessions - Aube électrique.wav','02 - Echo Sessions - Fragments.wav','03 - Atelier - Après minuit.wav','04 - Atelier - Horizon rose.wav','05 - Echo Sessions - Retour au calme.wav'])fs.writeFileSync(path.join(fixtures,name),wav);
fs.writeFileSync(path.join(profile,'media','config.json'),JSON.stringify({port:4320,token:'local-test-only',folders:[fixtures]}));
const app=await electron.launch({executablePath:path.join(root,process.env.ECHO_PACKAGED==='1'?'pc-app/dist/win-unpacked/Echo-All.exe':'pc-app/node_modules/electron/dist/electron.exe'),args:process.env.ECHO_PACKAGED==='1'?[]:[path.join(root,'pc-app')],env:{...process.env,ECHO_TEST_PROFILE:profile}});
let page;
try{
 page=await app.firstWindow();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.evaluate(()=>{window.__testCapture=[];const original=AudioContext.prototype.createMediaStreamDestination;AudioContext.prototype.createMediaStreamDestination=function(){const value=original.call(this);window.__testCapture.push(value);return value;};});
 await page.getByRole('heading',{name:'Mon espace.'}).waitFor();
 await page.getByText('5 titres',{exact:true}).waitFor();
 await page.screenshot({path:path.join(root,'pc-app/dist/home-0.25.png'),fullPage:false});
 await page.getByRole('button',{name:'Entrer dans le studio'}).click();
 await page.getByRole('button',{name:'Charger Aube électrique sur A'}).click();
 await page.locator('#deck-a .deck-name').getByText('Aube électrique',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Charger Fragments sur B'}).click();
 await page.locator('#deck-b .deck-name').getByText('Fragments',{exact:true}).waitFor();
 await page.locator('#deck-a [data-play]').click();
 await page.waitForFunction(()=>document.querySelector('#deck-a [data-position]').textContent!=='0:00');
 await page.locator('#deck-a [data-hot="0"]').click({modifiers:['Shift']});
 assert.equal(await page.locator('#deck-a [data-hot="0"]').evaluate(el=>el.classList.contains('saved')),true);
 await page.locator('#deck-a [data-loop="4"]').click();
 assert.equal(await page.locator('#deck-a [data-loop="4"]').evaluate(el=>el.classList.contains('active')),true);
 await page.locator('#deck-b [data-play]').click();
 assert.equal(await page.evaluate(async()=>{const context=new AudioContext();const input=context.createMediaStreamSource(window.__testCapture[0].stream);const analyser=context.createAnalyser();input.connect(analyser);await context.resume();await new Promise(r=>setTimeout(r,250));const samples=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(samples);const nonSilent=samples.some(n=>Math.abs(n)>.001);await context.close();return nonSilent;}),true);
 await page.locator('#deck-a [data-monitor]').click();
 assert.equal(await page.locator('#deck-a [data-monitor]').getAttribute('aria-pressed'),'true');
 await page.locator('#deck-a [data-monitor]').click();
 await page.getByRole('button',{name:'Enregistrer le mix',exact:false}).click();
 await page.waitForTimeout(2200);
 const mix=path.join(root,'.build-tmp','test-mix.webm');
 await app.evaluate(({session},target)=>{globalThis.__exportResult=null;session.defaultSession.once('will-download',(_event,item)=>{item.setSavePath(target);item.once('done',(_event,state)=>{globalThis.__exportResult=state;});});},mix);
 await page.getByRole('button',{name:'Arrêter et exporter',exact:false}).click();
 let exported=false;
 for(let attempt=0;attempt<100;attempt++){if(await app.evaluate(()=>globalThis.__exportResult==='completed')){exported=true;break;}await new Promise(r=>setTimeout(r,100));}
 assert.equal(exported,true,'Electron exported the mix');
 assert.ok(fs.statSync(mix).size>1000);assert.equal(fs.readFileSync(mix).subarray(0,4).toString('hex'),'1a45dfa3');
 await page.screenshot({path:path.join(root,'pc-app/dist/studio-0.25.png'),fullPage:false});
 await page.locator('#deck-a [data-loop="0"]').click();
 await page.locator('#deck-a [data-play]').click();await page.locator('#deck-b [data-play]').click();
 await page.getByRole('button',{name:'Notes & PDF'}).click();
 await app.waitForEvent('window');
 const windows=app.windows();const notes=windows.find(w=>w!==page);
 await notes.getByRole('heading',{name:'Un endroit pour tout retenir.'}).waitFor();
 await notes.getByRole('button',{name:'Noter une idée'}).click();
 await notes.getByLabel('Titre de la note',{exact:true}).fill('Mon prochain set');
 await notes.getByLabel('Contenu de la note',{exact:true}).fill('Préparer une transition douce entre les deux platines.\nTester la boucle et enregistrer le mix.');
 await notes.waitForFunction(()=>document.getElementById('save-status').textContent==='Enregistré sur cet appareil');
 await notes.screenshot({path:path.join(root,'pc-app/dist/notes-0.25.png'),fullPage:false});
 await notes.reload();
 await notes.getByText('Mon prochain set',{exact:true}).first().waitFor();
 const {PDFDocument}=await import('../notes/node_modules/pdf-lib/es/index.js').catch(()=>import('../notes/node_modules/pdf-lib/cjs/index.js'));
 const pdf=await PDFDocument.create();pdf.addPage([595,842]).drawText('Echo-All — Studio notes'.replace('—','-'),{x:60,y:760,size:20});
 const pdfPath=path.join(root,'.build-tmp','test-notes.pdf');fs.writeFileSync(pdfPath,await pdf.save());
 await notes.locator('#pdf-file').setInputFiles(pdfPath);
 await notes.waitForFunction(()=>!document.getElementById('drawing').hidden&&document.getElementById('pdf-canvas').width>0);
 const canvas=notes.locator('#ink-canvas');const box=await canvas.boundingBox();
 await notes.mouse.move(box.x+70,box.y+100);await notes.mouse.down();await notes.mouse.move(box.x+220,box.y+135,{steps:12});await notes.mouse.up();
 await notes.waitForFunction(()=>document.getElementById('save-status').textContent==='Enregistré sur cet appareil');
 await notes.close();
 const socialPromise=app.waitForEvent('window');await page.getByRole('link',{name:'Compte & amis'}).click();const social=await socialPromise;
 await social.getByRole('heading',{name:'Echo-All · Amis'}).waitFor();
 await social.getByRole('link',{name:'Ma bibliothèque'}).click();
 assert.deepEqual(errors,[]);
 console.log('PASS: accueil, vrai signal audio, platines, CUE, boucles, préécoute, export WebM valide, Notes persistantes, import PDF, annotation et fenêtre compte.');
}finally{await app.close();}
