package fr.nacre.media

import org.junit.Assert.*
import org.junit.Test

class YouTubeCatalogTest {
    @Test fun everyLinkShapeGivesTheVideoId() {
        assertEquals("dQw4w9WgXcQ", youtubeVideoId("https://www.youtube.com/watch?v=dQw4w9WgXcQ"))
        assertEquals("dQw4w9WgXcQ", youtubeVideoId("https://youtu.be/dQw4w9WgXcQ?t=42"))
        assertEquals("dQw4w9WgXcQ", youtubeVideoId("https://m.youtube.com/shorts/dQw4w9WgXcQ"))
        assertEquals("dQw4w9WgXcQ", youtubeVideoId("https://music.youtube.com/watch?v=dQw4w9WgXcQ&list=PL123"))
        assertEquals("dQw4w9WgXcQ", youtubeVideoId("youtube.com/embed/dQw4w9WgXcQ"))
        assertNull(youtubeVideoId("https://example.com/watch?v=dQw4w9WgXcQ"))
        assertNull(youtubeVideoId("juste du texte"))
    }

    @Test fun aSharedMessageStillYieldsItsLink() {
        assertEquals("dQw4w9WgXcQ", youtubeVideoId("Regarde ca : https://youtu.be/dQw4w9WgXcQ"))
        // Trailing punctuation belongs to the sentence, not to the address.
        assertEquals("dQw4w9WgXcQ", youtubeVideoId("Ecoute https://youtu.be/dQw4w9WgXcQ."))
    }

    @Test fun autoGeneratedMixesAreNotPlaylists() {
        assertEquals("PLabc-123_x", youtubePlaylistId("https://www.youtube.com/playlist?list=PLabc-123_x"))
        assertNull(youtubePlaylistId("https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ"))
        assertNull(youtubePlaylistId("https://www.youtube.com/playlist?list=WL"))
    }

    @Test fun channelsAreRecognisedButNeverVideos() {
        assertEquals("https://www.youtube.com/@ArteConcert", youtubeChannelUrl("https://www.youtube.com/@ArteConcert"))
        assertEquals("https://www.youtube.com/channel/UCabcdefghijklmnopqrstu",
            youtubeChannelUrl("https://www.youtube.com/channel/UCabcdefghijklmnopqrstu"))
        assertNull(youtubeChannelUrl("https://www.youtube.com/watch?v=dQw4w9WgXcQ"))
    }

    @Test fun promoTagsGoAwayButRealOnesStay() {
        assertEquals("Daft Punk - One More Time", cleanYouTubeTitle("Daft Punk - One More Time (Official Video)"))
        assertEquals("Titre", cleanYouTubeTitle("Titre [Official Music Video] (4K)"))
        assertEquals("Titre", cleanYouTubeTitle("Titre | Clip officiel"))
        assertEquals("Titre (Remix)", cleanYouTubeTitle("Titre (Remix) (Official Audio)"))
        assertEquals("Titre (feat. Quelqu'un)", cleanYouTubeTitle("Titre (feat. Quelqu'un) [HD]"))
        assertEquals("Titre (Live)", cleanYouTubeTitle("Titre (Live)"))
    }

    @Test fun artistComesFromTheTitleThenFromTheChannel() {
        assertEquals("Daft Punk" to "One More Time",
            youtubeArtistTitle("Daft Punk - One More Time (Official Video)", "DaftPunkVEVO"))
        // No separator: the auto-generated music channel names the artist.
        assertEquals("Orelsan" to "Basique", youtubeArtistTitle("Basique", "Orelsan - Topic"))
        assertEquals("Ma chaine" to "Une video", youtubeArtistTitle("Une video", "Ma chaine"))
        // An en dash is a separator too.
        assertEquals("A" to "B", youtubeArtistTitle("A – B", "Peu importe"))
    }

    @Test fun bitrateIsReadWhicheverUnitArrives() {
        assertEquals(128, normalizeKbps(128))
        assertEquals(128, normalizeKbps(128000))
        assertEquals(0, normalizeKbps(0))
    }

    @Test fun qualityTakesTheBestTrackUnderTheCeiling() {
        assertEquals(128, pickBitrate(listOf(48, 128, 160), 128))
        assertEquals(160, pickBitrate(listOf(48, 128, 160), 10_000))
        // Everything is above the ceiling: take the cheapest rather than nothing.
        assertEquals(128, pickBitrate(listOf(128, 160), 64))
        assertNull(pickBitrate(emptyList(), 128))
    }

    @Test fun formatSelectorsMatchTheChosenQuality() {
        assertEquals("bestaudio/best", audioFormatSelector(AudioQuality.BEST))
        assertEquals("bestaudio[abr<=64]/bestaudio/best", audioFormatSelector(AudioQuality.ECONOMY))
        assertEquals("bestvideo+bestaudio/best", videoFormatSelector(VideoQuality.MAX))
        assertTrue("height<=1080" in videoFormatSelector(VideoQuality.FHD))
    }

    @Test fun theLibraryKeepsAStableIdWhilePlaybackCarriesTheMarker() {
        val watch = youtubeWatchUrl("dQw4w9WgXcQ")
        val audio = youtubePlaybackUri(watch, false)
        val video = youtubePlaybackUri(watch, true)
        assertFalse(wantsVideoStream(audio))
        assertTrue(wantsVideoStream(video))
        // Both markers lead back to the same watch URL, so history and cue points stay attached to it.
        assertEquals(watch, cleanWatchUrl(audio))
        assertEquals(watch, cleanWatchUrl(video))
    }

    @Test fun countsAreReadableInFrench() {
        assertEquals("1,5 M de vues", formatViews(1_500_000))
        assertEquals("12 k vues", formatViews(12_000))
        assertEquals("1 vue", formatViews(1))
        assertEquals("", formatViews(-1))
    }

    @Test fun recentSearchesKeepTheLatestFirstWithoutRepeats() {
        assertEquals(listOf("b", "a"), pushRecent(listOf("a"), "b"))
        // Searching the same thing again moves it back to the front, in the spelling just typed.
        assertEquals(listOf("Orelsan", "Damso"), pushRecent(listOf("Damso", "orelsan"), "  Orelsan  "))
        assertEquals(listOf("a"), pushRecent(listOf("a"), "   "))
        assertEquals(2, pushRecent(listOf("a", "b"), "c", max = 2).size)
    }

    @Test fun fileNamesStayValidOnAndroid() {
        assertEquals("AC DC - Back in Black", youtubeFileBase("AC/DC", "Back in Black"))
        assertEquals("Sans artiste", youtubeFileBase("", "Sans artiste"))
    }
}
