import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.dirname(here),source=path.join(root,'social-web');
for(const [from,to]of [['index.html','social.html'],['social.mjs','social.mjs']])fs.copyFileSync(path.join(source,from),path.join(here,'web',to));
const config=path.join(source,'firebase-config.json');
fs.copyFileSync(fs.existsSync(config)?config:path.join(source,'firebase-config.example.json'),path.join(here,'web','firebase-config.json'));
fs.copyFileSync(path.join(root,'app/src/main/res/drawable-nodpi/echo_logo.png'),path.join(here,'web','echo-logo.png'));
const notes=path.join(here,'notes');fs.mkdirSync(notes,{recursive:true});
for(const name of ['server.mjs','lan.mjs'])fs.copyFileSync(path.join(root,'notes',name),path.join(notes,name));
fs.cpSync(path.join(root,'notes','web'),path.join(notes,'web'),{recursive:true});
if(!fs.existsSync(path.join(notes,'web/vendor/pdf.mjs')))throw Error('Notes : exécute npm ci --prefix notes puis npm run vendor --prefix notes.');
